# perguntas.py

perguntas = [
    {"pergunta": "Eu me considero uma pessoa focada e determinada.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [8, 9, 1, 3]},
    {"pergunta": "Eu costumo evitar conflitos sempre que possível.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [9, 1, 2, 4]},
    {"pergunta": "Eu me preocupo muito com o que os outros pensam de mim.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [3, 4, 2, 6]},
    {"pergunta": "Eu gosto de seguir regras e tradições.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [1, 6, 9, 5]},
    {"pergunta": "Eu me sinto energizado ao ajudar outras pessoas.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [2, 7, 9, 4]},
    {"pergunta": "Eu prefiro estar sempre preparado para o pior.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [6, 1, 5, 8]},
    {"pergunta": "Eu gosto de ser o centro das atenções.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [3, 7, 8, 2]},
    {"pergunta": "Eu prefiro seguir meu próprio caminho do que seguir a multidão.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [4, 5, 1, 9]},
    {"pergunta": "Eu sou uma pessoa bastante reservada.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [5, 4, 9, 6]},
    {"pergunta": "Eu sou muito leal aos meus amigos e família.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [6, 2, 8, 1]},
    {"pergunta": "Eu gosto de buscar novos desafios e aventuras.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [7, 3, 8, 9]},
    {"pergunta": "Eu sou muito sensível às críticas.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [4, 2, 6, 3]},
    {"pergunta": "Eu prefiro estar no controle das situações.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [8, 1, 3, 5]},
    {"pergunta": "Eu sou uma pessoa que costuma planejar tudo com antecedência.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [1, 6, 5, 2]},
    {"pergunta": "Eu sou muito empático e consigo me colocar no lugar dos outros.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [2, 4, 9, 7]},
    {"pergunta": "Eu tenho facilidade em fazer amigos.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [7, 3, 2, 6]},
    {"pergunta": "Eu sou muito detalhista e perfeccionista.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [1, 4, 3, 5]},
    {"pergunta": "Eu tenho uma necessidade constante de ser reconhecido pelo que faço.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [3, 2, 4, 7]},
    {"pergunta": "Eu sou muito competitivo e odeio perder.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [8, 3, 1, 7]},
    {"pergunta": "Eu gosto de trabalhar em equipe e colaborar com os outros.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [2, 6, 9, 5]},
    {"pergunta": "Eu sou uma pessoa muito criativa e inovadora.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [4, 7, 3, 5]},
    {"pergunta": "Eu costumo procrastinar minhas tarefas.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [9, 4, 6, 7]},
    {"pergunta": "Eu sou muito independente e autossuficiente.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [5, 8, 4, 1]},
    {"pergunta": "Eu sou uma pessoa otimista e positiva.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [7, 2, 9, 6]},
    {"pergunta": "Eu sou muito meticuloso e organizado.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [1, 5, 3, 6]},
    {"pergunta": "Eu sou uma pessoa muito leal e protetora com quem amo.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [6, 8, 2, 4]},
    {"pergunta": "Eu sou uma pessoa calma e paciente.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [9, 5, 2, 7]},
    {"pergunta": "Eu gosto de assumir responsabilidades e liderar projetos.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [8, 3, 1, 6]},
    {"pergunta": "Eu sou uma pessoa muito introspectiva e reflexiva.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [5, 4, 9, 6]},
    {"pergunta": "Eu sou muito focado em alcançar meus objetivos.", "opcoes": ["Sim", "Não", "Às vezes", "Depende"], "resultado": [3, 8, 1, 7]},
]